services:
  - type: web
    name: dth-ipm-analyzer
    env: python
    buildCommand: |
      python3 -m pip install --upgrade pip
      python3 -m pip install -r requirements.txt
      python3 -m pip list
    startCommand: python3 -m uvicorn main:app --host 0.0.0.0 --port 10000
